### PR TITLE
Modernize packaging

### PR DESCRIPTION
**Pull request by grantjenks**
## Change Summary

The sdist published previously fails during install because of the pre-build dependency on "m2r". These changes modernize the packaging and remove the m2r dependency during install.
1. Use [build](https://pypi.org/project/build/) to build the wheel and sdist
2. Convert setup.py to pyproject.toml
3. Embed the version in the `__init__.py` so it is available after install

A new package (for testing) has been successfully published to https://pypi.org/project/typesense-alt/ .

TODO: The name "typesense-alt" should be changed before merge.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by kishorenc** [comment]
Thank you, this is great. I will be testing it out this week and merging.

**Review by kishorenc — APPROVED** [review]

**Comment by kishorenc** [comment]
@grantjenks 

I've merged these changes into a different branch and published a beta build with version `0.19.0b1`. Can you please try installing that and let me know if everything works well?

**Comment by grantjenks** [comment]
Unfortunately, I can't test a pre-release version with the infrastructure that I have.

But, I can confirm that a source-only install works from my machine:

```
$ pip install --no-binary :all: typesense==0.19.0b1
Collecting typesense==0.19.0b1
  Downloading typesense-0.19.0b1.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests (from typesense==0.19.0b1)
  Downloading requests-2.31.0.tar.gz (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting charset-normalizer<4,>=2 (from requests->typesense==0.19.0b1)
  Downloading charset-normalizer-3.3.2.tar.gz (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.8/104.8 kB 2.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting idna<4,>=2.5 (from requests->typesense==0.19.0b1)
  Downloading idna-3.6.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urllib3<3,>=1.21.1 (from requests->typesense==0.19.0b1)
  Downloading urllib3-2.1.0.tar.gz (263 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.9/263.9 kB 8.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting certifi>=2017.4.17 (from requests->typesense==0.19.0b1)
  Downloading certifi-2023.11.17.tar.gz (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.6/163.6 kB 9.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: typesense, requests, certifi, charset-normalizer, idna, urllib3
  Building wheel for typesense (pyproject.toml) ... done
  Created wheel for typesense: filename=typesense-0.19.0b1-py3-none-any.whl size=19436 sha256=9f97f685d3191413b289e1677a0e953c012d3daac913c0a6da59507d05199a18
  Stored in directory: /Users/gjenks/Library/Caches/pip/wheels/15/9e/57/7fcf56974d31ddccfd2896fbb8c48ffbe88a5fe171f87fba53
  Building wheel for requests (pyproject.toml) ... done
  Created wheel for requests: filename=requests-2.31.0-py3-none-any.whl size=62553 sha256=81cb1a50ad12120751b8a6afe60bd8258f11fd8ab7dd41edbc85cd844cd51fa7
  Stored in directory: /Users/gjenks/Library/Caches/pip/wheels/8a/86/cb/2f6e3767c8a70012d0ce3747d8ed504b501cd31b78a0664e9f
  Building wheel for certifi (pyproject.toml) ... done
  Created wheel for certifi: filename=certifi-2023.11.17-py3-none-any.whl size=162529 sha256=29f68c60504b592a378e9881d2c462bf34031ce7eff7c1919c2e4148fe1b79d4
  Stored in directory: /Users/gjenks/Library/Caches/pip/wheels/f2/f1/53/c20c61266c3a67f3023fa9d93da2202d86c673e7488950a149
  Building wheel for charset-normalizer (pyproject.toml) ... done
  Created wheel for charset-normalizer: filename=charset_normalizer-3.3.2-py3-none-any.whl size=48544 sha256=5e5847e697b761ba4485ccee63fc839711467a907f481c51e0c21c9839cd6c08
  Stored in directory: /Users/gjenks/Library/Caches/pip/wheels/ca/b6/df/24c4242b8f2116c5d5925df7562aaf5eaf7f02be143dbc93f1
  Building wheel for idna (pyproject.toml) ... done
  Created wheel for idna: filename=idna-3.6-py3-none-any.whl size=61567 sha256=c05567e9c24a6b9faaa835c4821bad0590fbb9d5779e7caa6e1cc4978e7eb24f
  Stored in directory: /Users/gjenks/Library/Caches/pip/wheels/1f/0c/31/9a287a81d9fb2f2cc4dd981bee0818dc9a35992bcdda32b9ca
  Building wheel for urllib3 (pyproject.toml) ... done
  Created wheel for urllib3: filename=urllib3-2.1.0-py3-none-any.whl size=104578 sha256=a638bd8d283304c4e644f4ce697b3a72df099d15be8650bbe6ec0a9b62a67e8b
  Stored in directory: /Users/gjenks/Library/Caches/pip/wheels/30/68/b3/165a223e0e504767d797ce55b355b3b086d12e333fbd8df9b4
Successfully built typesense requests certifi charset-normalizer idna urllib3
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, typesense
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 idna-3.6 requests-2.31.0 typesense-0.19.0b1 urllib3-2.1.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
(env310) 2024-01-02 16:09:45 gjenks @ gjenks-mn2 : /tmp/deleteme 
$ python
Python 3.10.12 (main, Jul 28 2023, 18:34:01) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import typesense
```

Notice these lines, specifically:
```
Collecting typesense==0.19.0b1
  Downloading typesense-0.19.0b1.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
```
are successful! ✔️

**Comment by grantjenks** [comment]
Please publish 0.19.0 when possible.

**Comment by kishorenc** [comment]
`0.19.0` has been published.

**Comment by grantjenks** [comment]
Success! Thank you so much.

**Pull request merged**
