### PR TITLE
Allow to pass verify parameter to API client

### PR DESCRIPTION
**Pull request by eliskovets**
## Change Summary
Add `verify` parameter to Configuration class. 
That should allow to use self signed SSL certificates. Fix for https://github.com/typesense/typesense-python/issues/42

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by kishorenc** [comment]
@eliskovets 

Thank you for the PR. Before I can merge this, I'm waiting to hear back from a contributor for another change I had merged and published a beta build for. Would you be able to try testing version `0.19.0b1` of the Typesense Python client and confirming that everything works? Then I can merge that change to the main branch and then review+merge this.

**Comment by eliskovets** [comment]
Hi @kishorenc , 
Sorry, it took me some time to get back to this PR. 
I've just tested `v0.19.0b1` and it works just fine.

**Comment by kishorenc** [comment]
@eliskovets 

Thank you for confirming! I have now merged those build changes into the main branch, but that's causing a conflict here. The fix is simple though: there is now a `src` directory at top which wraps the older `typesense` root level directory.

**Comment by eliskovets** [comment]
Thank you for update @kishorenc . I just synced it with master branch. 
Conflicts are resolved.

**Review by kishorenc — APPROVED** [review]

**Pull request merged**
